"""
生成 FIR PPG golden，并同步导出 C 头文件系数（完整 double）。

用法：uv run python -m python.generate_golden fir_ppg
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path
from typing import Any

import numpy as np

from .fir_prototype import (
    FS,
    NUMTAPS,
    FIRInputError,
    design_bandpass_coeffs,
    fir_filter,
    truncate_coeffs,
)

SEED = 42
CASE = "fir_ppg"


def _canonical_dump(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n"


def _write_c_header(coeffs: np.ndarray, path: Path) -> None:
    """把系数写成 C 字面量；必须用 %.17g，避免 6 位有效数字陷阱。"""
    lines = [
        "#ifndef ALGO_FIR_COEFFS_H",
        "#define ALGO_FIR_COEFFS_H",
        "",
        "/* AUTO-GENERATED by python/generate_fir_ppg.py — do not edit by hand. */",
        f"/* fs={FS} Hz, taps={NUMTAPS}, band=0.5-4 Hz, window=hamming */",
        "",
        f"#define ALGO_FIR_NUM_TAPS {NUMTAPS}",
        "",
        "static const double ALGO_FIR_BANDPASS_COEFFS[ALGO_FIR_NUM_TAPS] = {",
    ]
    for i, c in enumerate(coeffs):
        comma = "," if i + 1 < len(coeffs) else ""
        lines.append(f"    {c:.17g}{comma}")
    lines += ["};", "", "#endif /* ALGO_FIR_COEFFS_H */", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def _record(
    idx: int,
    category: str,
    pathology: str,
    x: list[float],
    coeffs: np.ndarray,
    *,
    non_finite_mode: str | None = None,
) -> dict[str, Any]:
    serializable = [0.0 if (isinstance(v, float) and not math.isfinite(v)) else float(v) for v in x]
    base: dict[str, Any] = {
        "id": f"fir_{idx:03d}",
        "case": CASE,
        "category": category,
        "pathology": pathology,
        "input": {"x": serializable, "non_finite_mode": non_finite_mode},
        "meta": {
            "seed": SEED,
            "generator": "python/fir_prototype.py",
            "source": "synthetic",
            "license_note": "synthetic internal",
            "fs_hz": FS,
            "num_taps": NUMTAPS,
        },
    }
    try:
        y = fir_filter(x, coeffs)
        base["expected"] = {"y": y.tolist(), "ok": True, "error": None}
        base["snapshots"] = {}
    except FIRInputError as exc:
        base["expected"] = {"y": None, "ok": False, "error": exc.code}
        base["snapshots"] = {}
    return base


def _sine(fs: float, freq: float, seconds: float, amp: float = 1.0) -> list[float]:
    n = int(fs * seconds)
    t = np.arange(n) / fs
    return (amp * np.sin(2 * np.pi * freq * t)).tolist()


def build_dataset(coeffs: np.ndarray) -> list[dict[str, Any]]:
    rng = random.Random(SEED)
    rows: list[dict[str, Any]] = []
    i = 1

    # 通带内正弦（应接近通过）
    for freq in (1.0, 1.5, 2.0, 2.5):
        rows.append(_record(i, "normal", "none", _sine(FS, freq, 4.0), coeffs))
        i += 1

    # 混合：通带 + 少量噪声
    for _ in range(18):
        x = np.array(_sine(FS, 1.2, 3.0))
        noise = np.array([rng.uniform(-0.05, 0.05) for _ in range(len(x))])
        x = x + noise
        rows.append(_record(i, "normal", "none", x.tolist(), coeffs))
        i += 1

    # 边界：短序列、直流
    rows.append(_record(i, "boundary", "none", [0.0], coeffs))
    i += 1
    rows.append(_record(i, "boundary", "none", [1.0] * 10, coeffs))
    i += 1
    rows.append(_record(i, "boundary", "none", _sine(FS, 0.8, 1.0), coeffs))
    i += 1

    # 阻带正弦（应被大幅衰减）——仍算正常计算路径
    for freq in (0.1, 8.0, 10.0):
        rows.append(_record(i, "boundary", "stopband_tone", _sine(FS, freq, 4.0), coeffs))
        i += 1

    # 病态
    rows.append(_record(i, "pathological", "empty", [], coeffs))
    i += 1
    rows.append(
        _record(
            i,
            "pathological",
            "non_finite",
            [0.0, float("nan"), 0.1],
            coeffs,
            non_finite_mode="nan_at_1",
        )
    )
    i += 1
    rows.append(
        _record(
            i,
            "pathological",
            "non_finite",
            [0.0, float("inf")],
            coeffs,
            non_finite_mode="inf_at_1",
        )
    )
    i += 1

    for _ in range(12):
        x = [rng.uniform(-2.0, 2.0) for _ in range(80)]
        rows.append(_record(i, "pathological", "extreme_noise", x, coeffs))
        i += 1

    for _ in range(8):
        # 突发尖峰
        x = np.array(_sine(FS, 1.0, 3.0))
        x[20] = 5.0
        rows.append(_record(i, "pathological", "spike", x.tolist(), coeffs))
        i += 1

    return rows


def write_golden(repo: Path) -> tuple[int, float]:
    coeffs = design_bandpass_coeffs()
    out_dir = repo / "golden" / CASE
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.json"):
        old.unlink()

    # 系数单独冻结，供 Swift/测试核对
    coeffs_path = out_dir / "coeffs.json"
    truncated = truncate_coeffs(coeffs, 3)
    # 用同一输入展示截断系数的误差（写入 meta 演示，不进 parity 主路径）
    demo_x = _sine(FS, 1.0, 2.0)
    y_full = fir_filter(demo_x, coeffs)
    y_trunc = fir_filter(demo_x, truncated)
    max_abs_err = float(np.max(np.abs(y_full - y_trunc)))
    coeffs_path.write_text(
        _canonical_dump(
            {
                "fs_hz": FS,
                "num_taps": NUMTAPS,
                "band_hz": [0.5, 4.0],
                "window": "hamming",
                "coeffs": coeffs.tolist(),
                "truncation_demo": {
                    "significant_digits": 3,
                    "max_abs_error_on_1hz_sine": max_abs_err,
                    "note": "Aggressive digit truncation destroys response; default export uses full double (%.17g)",
                },
            }
        ),
        encoding="utf-8",
    )

    header = repo / "Sources" / "AlgoC" / "include" / "algo_fir_coeffs.h"
    _write_c_header(coeffs, header)

    rows = build_dataset(coeffs)
    for row in rows:
        (out_dir / f"{row['id']}.json").write_text(_canonical_dump(row), encoding="utf-8")

    pathological = sum(1 for r in rows if r["category"] == "pathological")
    ratio = pathological / len(rows)
    print(f"truncation_demo max_abs_error={max_abs_err:.6g}")
    return len(rows), ratio


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    n, ratio = write_golden(root)
    print(f"wrote {n} records (pathological_ratio={ratio:.2%})")
    if n < 50:
        print("ERROR: need >= 50 records")
        return 1
    if ratio < 0.40:
        print("ERROR: pathological ratio < 40%")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
